// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancellation`, `invalid_request`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterBridge>>
abstract class FlutterBridge implements RustOpaqueInterface {
  bool cancel({required BigInt id});

  BigInt createCancellation();

  static Future<FlutterBridge> default_() =>
      RustLib.instance.api.crateApiFlutterBridgeDefault();

  factory FlutterBridge() => RustLib.instance.api.crateApiFlutterBridgeNew();

  Future<FlutterDocumentSummary> openDocument({
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  });

  bool releaseBuffer({required FlutterBufferHandle handle});

  bool releaseCancellation({required BigInt id});

  bool releaseDocument({required FlutterDocumentHandle handle});

  Future<FlutterRenderedBuffer> renderPage({
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  });

  Uint8List takeBuffer({required FlutterBufferHandle handle});
}

enum FlutterBookFormat { pdf, epub, cbz }

class FlutterBridgeError implements FrbException {
  final FlutterBridgeErrorKind kind;
  final String message;

  const FlutterBridgeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum FlutterBridgeErrorKind {
  cancelled,
  notFound,
  inaccessible,
  unsupported,
  invalidRequest,
  malformed,
  limitExceeded,
  backendUnavailable,
  renderFailed,
}

class FlutterBufferHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterBufferHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBufferHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterDocumentHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentSummary {
  final FlutterDocumentHandle handle;
  final FlutterBookFormat format;
  final String? title;
  final BigInt logicalUnitCount;

  const FlutterDocumentSummary({
    required this.handle,
    required this.format,
    this.title,
    required this.logicalUnitCount,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      format.hashCode ^
      title.hashCode ^
      logicalUnitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentSummary &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          format == other.format &&
          title == other.title &&
          logicalUnitCount == other.logicalUnitCount;
}

class FlutterOpenRequest {
  final String localId;
  final String pathKey;
  final FlutterBookFormat? formatHint;

  const FlutterOpenRequest({
    required this.localId,
    required this.pathKey,
    this.formatHint,
  });

  @override
  int get hashCode => localId.hashCode ^ pathKey.hashCode ^ formatHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterOpenRequest &&
          runtimeType == other.runtimeType &&
          localId == other.localId &&
          pathKey == other.pathKey &&
          formatHint == other.formatHint;
}

class FlutterRenderedBuffer {
  final FlutterBufferHandle handle;
  final int width;
  final int height;
  final BigInt byteLen;

  const FlutterRenderedBuffer({
    required this.handle,
    required this.width,
    required this.height,
    required this.byteLen,
  });

  @override
  int get hashCode =>
      handle.hashCode ^ width.hashCode ^ height.hashCode ^ byteLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRenderedBuffer &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          byteLen == other.byteLen;
}
