// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancellation`, `from_bridge`, `invalid_request`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterBridge>>
abstract class FlutterBridge implements RustOpaqueInterface {
  bool cancel({required BigInt id});

  Future<FlutterAnnotation> createAnnotation({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required BigInt start,
    required BigInt end,
    required FlutterHighlightColor color,
    String? body,
    required BigInt cancellationId,
  });

  BigInt createCancellation();

  static Future<FlutterBridge> default_() =>
      RustLib.instance.api.crateApiFlutterBridgeDefault();

  Future<bool> deleteAnnotation({
    required FlutterDocumentHandle document,
    required String id,
  });

  Future<List<FlutterAnnotation>> listAnnotations({
    required FlutterDocumentHandle document,
  });

  factory FlutterBridge() => RustLib.instance.api.crateApiFlutterBridgeNew();

  Future<FlutterDocumentSummary> openDocument({
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  });

  bool releaseBuffer({required FlutterBufferHandle handle});

  bool releaseCancellation({required BigInt id});

  bool releaseDocument({required FlutterDocumentHandle handle});

  bool releaseSelection({required FlutterSelectionHandle handle});

  Future<FlutterRenderedBuffer> renderPage({
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  });

  Future<FlutterSelectionSurface> selectionSurface({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required double scale,
    required double width,
    required double fontSize,
    required BigInt cancellationId,
  });

  Uint8List takeBuffer({required FlutterBufferHandle handle});

  Future<bool> updateAnnotation({
    required FlutterDocumentHandle document,
    required String id,
    required FlutterHighlightColor color,
    String? body,
  });

  /// Construct a bridge with a host-provided SQLite database path.
  static FlutterBridge withDatabasePath({required String databasePath}) =>
      RustLib.instance.api.crateApiFlutterBridgeWithDatabasePath(
        databasePath: databasePath,
      );
}

class FlutterAnnotation {
  final String id;
  final BigInt unit;
  final BigInt start;
  final BigInt end;
  final FlutterHighlightColor color;
  final String? body;

  const FlutterAnnotation({
    required this.id,
    required this.unit,
    required this.start,
    required this.end,
    required this.color,
    this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      unit.hashCode ^
      start.hashCode ^
      end.hashCode ^
      color.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterAnnotation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          unit == other.unit &&
          start == other.start &&
          end == other.end &&
          color == other.color &&
          body == other.body;
}

enum FlutterBookFormat { pdf, epub, cbz }

class FlutterBridgeError implements FrbException {
  final FlutterBridgeErrorKind kind;
  final String message;

  const FlutterBridgeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum FlutterBridgeErrorKind {
  cancelled,
  notFound,
  inaccessible,
  unsupported,
  invalidRequest,
  malformed,
  limitExceeded,
  backendUnavailable,
  renderFailed,
}

class FlutterBufferHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterBufferHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBufferHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterDocumentHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentSummary {
  final FlutterDocumentHandle handle;
  final FlutterBookFormat format;
  final String? title;
  final BigInt logicalUnitCount;

  const FlutterDocumentSummary({
    required this.handle,
    required this.format,
    this.title,
    required this.logicalUnitCount,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      format.hashCode ^
      title.hashCode ^
      logicalUnitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentSummary &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          format == other.format &&
          title == other.title &&
          logicalUnitCount == other.logicalUnitCount;
}

enum FlutterHighlightColor { yellow, green, blue, pink, purple }

class FlutterOpenRequest {
  final String localId;
  final String pathKey;
  final FlutterBookFormat? formatHint;

  const FlutterOpenRequest({
    required this.localId,
    required this.pathKey,
    this.formatHint,
  });

  @override
  int get hashCode => localId.hashCode ^ pathKey.hashCode ^ formatHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterOpenRequest &&
          runtimeType == other.runtimeType &&
          localId == other.localId &&
          pathKey == other.pathKey &&
          formatHint == other.formatHint;
}

class FlutterRenderedBuffer {
  final FlutterBufferHandle handle;
  final int width;
  final int height;
  final BigInt byteLen;

  const FlutterRenderedBuffer({
    required this.handle,
    required this.width,
    required this.height,
    required this.byteLen,
  });

  @override
  int get hashCode =>
      handle.hashCode ^ width.hashCode ^ height.hashCode ^ byteLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRenderedBuffer &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          byteLen == other.byteLen;
}

class FlutterSelectionCaret {
  final BigInt offset;
  final double x;
  final double top;
  final double bottom;

  const FlutterSelectionCaret({
    required this.offset,
    required this.x,
    required this.top,
    required this.bottom,
  });

  @override
  int get hashCode =>
      offset.hashCode ^ x.hashCode ^ top.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionCaret &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          x == other.x &&
          top == other.top &&
          bottom == other.bottom;
}

class FlutterSelectionEndpoint {
  final BigInt offset;
  final BigInt rangeStart;
  final BigInt rangeEnd;
  final FlutterSelectionRect rect;

  const FlutterSelectionEndpoint({
    required this.offset,
    required this.rangeStart,
    required this.rangeEnd,
    required this.rect,
  });

  @override
  int get hashCode =>
      offset.hashCode ^ rangeStart.hashCode ^ rangeEnd.hashCode ^ rect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionEndpoint &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd &&
          rect == other.rect;
}

class FlutterSelectionHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterSelectionHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterSelectionRect {
  final double left;
  final double top;
  final double right;
  final double bottom;

  const FlutterSelectionRect({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ right.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionRect &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}

class FlutterSelectionSurface {
  final FlutterSelectionHandle handle;
  final double width;
  final double height;
  final String text;
  final String? resourcePath;
  final FlutterRenderedBuffer? raster;
  final List<FlutterSelectionEndpoint> endpoints;
  final Uint32List graphemeBoundaries;
  final Uint32List wordBoundaries;
  final List<FlutterSelectionVisualLine> visualLines;

  const FlutterSelectionSurface({
    required this.handle,
    required this.width,
    required this.height,
    required this.text,
    this.resourcePath,
    this.raster,
    required this.endpoints,
    required this.graphemeBoundaries,
    required this.wordBoundaries,
    required this.visualLines,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      width.hashCode ^
      height.hashCode ^
      text.hashCode ^
      resourcePath.hashCode ^
      raster.hashCode ^
      endpoints.hashCode ^
      graphemeBoundaries.hashCode ^
      wordBoundaries.hashCode ^
      visualLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionSurface &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          text == other.text &&
          resourcePath == other.resourcePath &&
          raster == other.raster &&
          endpoints == other.endpoints &&
          graphemeBoundaries == other.graphemeBoundaries &&
          wordBoundaries == other.wordBoundaries &&
          visualLines == other.visualLines;
}

class FlutterSelectionVisualLine {
  final List<FlutterSelectionCaret> carets;

  const FlutterSelectionVisualLine({required this.carets});

  @override
  int get hashCode => carets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionVisualLine &&
          runtimeType == other.runtimeType &&
          carets == other.carets;
}
