// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlutterBridgePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr;

  @protected
  FlutterBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  FlutterBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  FlutterBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FlutterBookFormat dco_decode_box_autoadd_flutter_book_format(dynamic raw);

  @protected
  FlutterBufferHandle dco_decode_box_autoadd_flutter_buffer_handle(dynamic raw);

  @protected
  FlutterDocumentHandle dco_decode_box_autoadd_flutter_document_handle(
    dynamic raw,
  );

  @protected
  FlutterOpenRequest dco_decode_box_autoadd_flutter_open_request(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FlutterBookFormat dco_decode_flutter_book_format(dynamic raw);

  @protected
  FlutterBridgeError dco_decode_flutter_bridge_error(dynamic raw);

  @protected
  FlutterBridgeErrorKind dco_decode_flutter_bridge_error_kind(dynamic raw);

  @protected
  FlutterBufferHandle dco_decode_flutter_buffer_handle(dynamic raw);

  @protected
  FlutterDocumentHandle dco_decode_flutter_document_handle(dynamic raw);

  @protected
  FlutterDocumentSummary dco_decode_flutter_document_summary(dynamic raw);

  @protected
  FlutterOpenRequest dco_decode_flutter_open_request(dynamic raw);

  @protected
  FlutterRenderedBuffer dco_decode_flutter_rendered_buffer(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FlutterBookFormat? dco_decode_opt_box_autoadd_flutter_book_format(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  FlutterBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FlutterBookFormat sse_decode_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBufferHandle sse_decode_box_autoadd_flutter_buffer_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentHandle sse_decode_box_autoadd_flutter_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterOpenRequest sse_decode_box_autoadd_flutter_open_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FlutterBookFormat sse_decode_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridgeError sse_decode_flutter_bridge_error(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridgeErrorKind sse_decode_flutter_bridge_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBufferHandle sse_decode_flutter_buffer_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentHandle sse_decode_flutter_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentSummary sse_decode_flutter_document_summary(
    SseDeserializer deserializer,
  );

  @protected
  FlutterOpenRequest sse_decode_flutter_open_request(
    SseDeserializer deserializer,
  );

  @protected
  FlutterRenderedBuffer sse_decode_flutter_rendered_buffer(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FlutterBookFormat? sse_decode_opt_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_bridge_error(
    FlutterBridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_bridge_error_kind(
    FlutterBridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_document_summary(
    FlutterDocumentSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_flutter_book_format(
    FlutterBookFormat? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shosai_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shosai_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
