// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1364596129;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'shosai_flutter_bridge',
        ioDirectory: '../crates/shosai-flutter-bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiFlutterBridgeCancel({
    required FlutterBridge that,
    required BigInt id,
  });

  Future<FlutterAnnotation> crateApiFlutterBridgeCreateAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt unit,
    required BigInt start,
    required BigInt end,
    required FlutterHighlightColor color,
    String? body,
    required BigInt cancellationId,
  });

  BigInt crateApiFlutterBridgeCreateCancellation({required FlutterBridge that});

  Future<FlutterBridge> crateApiFlutterBridgeDefault();

  Future<bool> crateApiFlutterBridgeDeleteAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required String id,
  });

  Future<List<FlutterAnnotation>> crateApiFlutterBridgeListAnnotations({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
  });

  FlutterBridge crateApiFlutterBridgeNew();

  Future<FlutterDocumentSummary> crateApiFlutterBridgeOpenDocument({
    required FlutterBridge that,
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  });

  bool crateApiFlutterBridgeReleaseBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  });

  bool crateApiFlutterBridgeReleaseCancellation({
    required FlutterBridge that,
    required BigInt id,
  });

  bool crateApiFlutterBridgeReleaseDocument({
    required FlutterBridge that,
    required FlutterDocumentHandle handle,
  });

  bool crateApiFlutterBridgeReleaseSelection({
    required FlutterBridge that,
    required FlutterSelectionHandle handle,
  });

  Future<FlutterRenderedBuffer> crateApiFlutterBridgeRenderPage({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  });

  Future<FlutterSelectionSurface> crateApiFlutterBridgeSelectionSurface({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt unit,
    required double scale,
    required double width,
    required double fontSize,
    required BigInt cancellationId,
  });

  Uint8List crateApiFlutterBridgeTakeBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  });

  Future<bool> crateApiFlutterBridgeUpdateAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required String id,
    required FlutterHighlightColor color,
    String? body,
  });

  FlutterBridge crateApiFlutterBridgeWithDatabasePath({
    required String databasePath,
  });

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlutterBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlutterBridge;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlutterBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiFlutterBridgeCancel({
    required FlutterBridge that,
    required BigInt id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_u_64(id);
          return wire.wire__crate__api__FlutterBridge_cancel(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeCancelConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeCancelConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_cancel",
        argNames: ["that", "id"],
      );

  @override
  Future<FlutterAnnotation> crateApiFlutterBridgeCreateAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt unit,
    required BigInt start,
    required BigInt end,
    required FlutterHighlightColor color,
    String? body,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          var arg2 = cst_encode_usize(unit);
          var arg3 = cst_encode_usize(start);
          var arg4 = cst_encode_usize(end);
          var arg5 = cst_encode_flutter_highlight_color(color);
          var arg6 = cst_encode_opt_String(body);
          var arg7 = cst_encode_u_64(cancellationId);
          return wire.wire__crate__api__FlutterBridge_create_annotation(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
            arg7,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_flutter_annotation,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeCreateAnnotationConstMeta,
        argValues: [
          that,
          document,
          unit,
          start,
          end,
          color,
          body,
          cancellationId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeCreateAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_create_annotation",
        argNames: [
          "that",
          "document",
          "unit",
          "start",
          "end",
          "color",
          "body",
          "cancellationId",
        ],
      );

  @override
  BigInt crateApiFlutterBridgeCreateCancellation({
    required FlutterBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          return wire.wire__crate__api__FlutterBridge_create_cancellation(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_64,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeCreateCancellationConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeCreateCancellationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_create_cancellation",
        argNames: ["that"],
      );

  @override
  Future<FlutterBridge> crateApiFlutterBridgeDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__FlutterBridge_default(port_);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeDefaultConstMeta =>
      const TaskConstMeta(debugName: "FlutterBridge_default", argNames: []);

  @override
  Future<bool> crateApiFlutterBridgeDeleteAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          var arg2 = cst_encode_String(id);
          return wire.wire__crate__api__FlutterBridge_delete_annotation(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeDeleteAnnotationConstMeta,
        argValues: [that, document, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeDeleteAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_delete_annotation",
        argNames: ["that", "document", "id"],
      );

  @override
  Future<List<FlutterAnnotation>> crateApiFlutterBridgeListAnnotations({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          return wire.wire__crate__api__FlutterBridge_list_annotations(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_flutter_annotation,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeListAnnotationsConstMeta,
        argValues: [that, document],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeListAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_list_annotations",
        argNames: ["that", "document"],
      );

  @override
  FlutterBridge crateApiFlutterBridgeNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__FlutterBridge_new();
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeNewConstMeta =>
      const TaskConstMeta(debugName: "FlutterBridge_new", argNames: []);

  @override
  Future<FlutterDocumentSummary> crateApiFlutterBridgeOpenDocument({
    required FlutterBridge that,
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_open_request(request);
          var arg2 = cst_encode_u_64(cancellationId);
          return wire.wire__crate__api__FlutterBridge_open_document(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_flutter_document_summary,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeOpenDocumentConstMeta,
        argValues: [that, request, cancellationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeOpenDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_open_document",
        argNames: ["that", "request", "cancellationId"],
      );

  @override
  bool crateApiFlutterBridgeReleaseBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_buffer_handle(handle);
          return wire.wire__crate__api__FlutterBridge_release_buffer(
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseBufferConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseBufferConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_buffer",
        argNames: ["that", "handle"],
      );

  @override
  bool crateApiFlutterBridgeReleaseCancellation({
    required FlutterBridge that,
    required BigInt id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_u_64(id);
          return wire.wire__crate__api__FlutterBridge_release_cancellation(
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseCancellationConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseCancellationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_cancellation",
        argNames: ["that", "id"],
      );

  @override
  bool crateApiFlutterBridgeReleaseDocument({
    required FlutterBridge that,
    required FlutterDocumentHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(handle);
          return wire.wire__crate__api__FlutterBridge_release_document(
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseDocumentConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_document",
        argNames: ["that", "handle"],
      );

  @override
  bool crateApiFlutterBridgeReleaseSelection({
    required FlutterBridge that,
    required FlutterSelectionHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_selection_handle(handle);
          return wire.wire__crate__api__FlutterBridge_release_selection(
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseSelectionConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_selection",
        argNames: ["that", "handle"],
      );

  @override
  Future<FlutterRenderedBuffer> crateApiFlutterBridgeRenderPage({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          var arg2 = cst_encode_usize(page);
          var arg3 = cst_encode_f_32(scale);
          var arg4 = cst_encode_u_64(cancellationId);
          return wire.wire__crate__api__FlutterBridge_render_page(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_flutter_rendered_buffer,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeRenderPageConstMeta,
        argValues: [that, document, page, scale, cancellationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeRenderPageConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_render_page",
        argNames: ["that", "document", "page", "scale", "cancellationId"],
      );

  @override
  Future<FlutterSelectionSurface> crateApiFlutterBridgeSelectionSurface({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt unit,
    required double scale,
    required double width,
    required double fontSize,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          var arg2 = cst_encode_usize(unit);
          var arg3 = cst_encode_f_32(scale);
          var arg4 = cst_encode_f_32(width);
          var arg5 = cst_encode_f_32(fontSize);
          var arg6 = cst_encode_u_64(cancellationId);
          return wire.wire__crate__api__FlutterBridge_selection_surface(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_flutter_selection_surface,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeSelectionSurfaceConstMeta,
        argValues: [
          that,
          document,
          unit,
          scale,
          width,
          fontSize,
          cancellationId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeSelectionSurfaceConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_selection_surface",
        argNames: [
          "that",
          "document",
          "unit",
          "scale",
          "width",
          "fontSize",
          "cancellationId",
        ],
      );

  @override
  Uint8List crateApiFlutterBridgeTakeBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_buffer_handle(handle);
          return wire.wire__crate__api__FlutterBridge_take_buffer(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeTakeBufferConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeTakeBufferConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_take_buffer",
        argNames: ["that", "handle"],
      );

  @override
  Future<bool> crateApiFlutterBridgeUpdateAnnotation({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required String id,
    required FlutterHighlightColor color,
    String? body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
                that,
              );
          var arg1 = cst_encode_box_autoadd_flutter_document_handle(document);
          var arg2 = cst_encode_String(id);
          var arg3 = cst_encode_flutter_highlight_color(color);
          var arg4 = cst_encode_opt_String(body);
          return wire.wire__crate__api__FlutterBridge_update_annotation(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeUpdateAnnotationConstMeta,
        argValues: [that, document, id, color, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeUpdateAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_update_annotation",
        argNames: ["that", "document", "id", "color", "body"],
      );

  @override
  FlutterBridge crateApiFlutterBridgeWithDatabasePath({
    required String databasePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(databasePath);
          return wire.wire__crate__api__FlutterBridge_with_database_path(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeWithDatabasePathConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeWithDatabasePathConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_with_database_path",
        argNames: ["databasePath"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__init_app(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlutterBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlutterBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge;

  @protected
  FlutterBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterBookFormat dco_decode_box_autoadd_flutter_book_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_book_format(raw);
  }

  @protected
  FlutterBufferHandle dco_decode_box_autoadd_flutter_buffer_handle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_buffer_handle(raw);
  }

  @protected
  FlutterDocumentHandle dco_decode_box_autoadd_flutter_document_handle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_document_handle(raw);
  }

  @protected
  FlutterOpenRequest dco_decode_box_autoadd_flutter_open_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_open_request(raw);
  }

  @protected
  FlutterRenderedBuffer dco_decode_box_autoadd_flutter_rendered_buffer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_rendered_buffer(raw);
  }

  @protected
  FlutterSelectionHandle dco_decode_box_autoadd_flutter_selection_handle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_selection_handle(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FlutterAnnotation dco_decode_flutter_annotation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FlutterAnnotation(
      id: dco_decode_String(arr[0]),
      unit: dco_decode_usize(arr[1]),
      start: dco_decode_usize(arr[2]),
      end: dco_decode_usize(arr[3]),
      color: dco_decode_flutter_highlight_color(arr[4]),
      body: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  FlutterBookFormat dco_decode_flutter_book_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBookFormat.values[raw as int];
  }

  @protected
  FlutterBridgeError dco_decode_flutter_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterBridgeError(
      kind: dco_decode_flutter_bridge_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  FlutterBridgeErrorKind dco_decode_flutter_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeErrorKind.values[raw as int];
  }

  @protected
  FlutterBufferHandle dco_decode_flutter_buffer_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterBufferHandle(
      registry: dco_decode_u_64(arr[0]),
      id: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FlutterDocumentHandle dco_decode_flutter_document_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterDocumentHandle(
      registry: dco_decode_u_64(arr[0]),
      id: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FlutterDocumentSummary dco_decode_flutter_document_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterDocumentSummary(
      handle: dco_decode_flutter_document_handle(arr[0]),
      format: dco_decode_flutter_book_format(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      logicalUnitCount: dco_decode_usize(arr[3]),
    );
  }

  @protected
  FlutterHighlightColor dco_decode_flutter_highlight_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterHighlightColor.values[raw as int];
  }

  @protected
  FlutterOpenRequest dco_decode_flutter_open_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FlutterOpenRequest(
      localId: dco_decode_String(arr[0]),
      pathKey: dco_decode_String(arr[1]),
      formatHint: dco_decode_opt_box_autoadd_flutter_book_format(arr[2]),
    );
  }

  @protected
  FlutterRenderedBuffer dco_decode_flutter_rendered_buffer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterRenderedBuffer(
      handle: dco_decode_flutter_buffer_handle(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      byteLen: dco_decode_usize(arr[3]),
    );
  }

  @protected
  FlutterSelectionEndpoint dco_decode_flutter_selection_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterSelectionEndpoint(
      offset: dco_decode_usize(arr[0]),
      rangeStart: dco_decode_usize(arr[1]),
      rangeEnd: dco_decode_usize(arr[2]),
      rect: dco_decode_flutter_selection_rect(arr[3]),
    );
  }

  @protected
  FlutterSelectionHandle dco_decode_flutter_selection_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterSelectionHandle(
      registry: dco_decode_u_64(arr[0]),
      id: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FlutterSelectionRect dco_decode_flutter_selection_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterSelectionRect(
      left: dco_decode_f_32(arr[0]),
      top: dco_decode_f_32(arr[1]),
      right: dco_decode_f_32(arr[2]),
      bottom: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  FlutterSelectionSurface dco_decode_flutter_selection_surface(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FlutterSelectionSurface(
      handle: dco_decode_flutter_selection_handle(arr[0]),
      width: dco_decode_f_32(arr[1]),
      height: dco_decode_f_32(arr[2]),
      text: dco_decode_String(arr[3]),
      resourcePath: dco_decode_opt_String(arr[4]),
      raster: dco_decode_opt_box_autoadd_flutter_rendered_buffer(arr[5]),
      endpoints: dco_decode_list_flutter_selection_endpoint(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<FlutterAnnotation> dco_decode_list_flutter_annotation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_annotation).toList();
  }

  @protected
  List<FlutterSelectionEndpoint> dco_decode_list_flutter_selection_endpoint(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_flutter_selection_endpoint)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FlutterBookFormat? dco_decode_opt_box_autoadd_flutter_book_format(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_flutter_book_format(raw);
  }

  @protected
  FlutterRenderedBuffer? dco_decode_opt_box_autoadd_flutter_rendered_buffer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_flutter_rendered_buffer(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  FlutterBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlutterBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlutterBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterBookFormat sse_decode_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_book_format(deserializer));
  }

  @protected
  FlutterBufferHandle sse_decode_box_autoadd_flutter_buffer_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_buffer_handle(deserializer));
  }

  @protected
  FlutterDocumentHandle sse_decode_box_autoadd_flutter_document_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_document_handle(deserializer));
  }

  @protected
  FlutterOpenRequest sse_decode_box_autoadd_flutter_open_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_open_request(deserializer));
  }

  @protected
  FlutterRenderedBuffer sse_decode_box_autoadd_flutter_rendered_buffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_rendered_buffer(deserializer));
  }

  @protected
  FlutterSelectionHandle sse_decode_box_autoadd_flutter_selection_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_selection_handle(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FlutterAnnotation sse_decode_flutter_annotation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_unit = sse_decode_usize(deserializer);
    var var_start = sse_decode_usize(deserializer);
    var var_end = sse_decode_usize(deserializer);
    var var_color = sse_decode_flutter_highlight_color(deserializer);
    var var_body = sse_decode_opt_String(deserializer);
    return FlutterAnnotation(
      id: var_id,
      unit: var_unit,
      start: var_start,
      end: var_end,
      color: var_color,
      body: var_body,
    );
  }

  @protected
  FlutterBookFormat sse_decode_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterBookFormat.values[inner];
  }

  @protected
  FlutterBridgeError sse_decode_flutter_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_flutter_bridge_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return FlutterBridgeError(kind: var_kind, message: var_message);
  }

  @protected
  FlutterBridgeErrorKind sse_decode_flutter_bridge_error_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterBridgeErrorKind.values[inner];
  }

  @protected
  FlutterBufferHandle sse_decode_flutter_buffer_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registry = sse_decode_u_64(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    return FlutterBufferHandle(registry: var_registry, id: var_id);
  }

  @protected
  FlutterDocumentHandle sse_decode_flutter_document_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registry = sse_decode_u_64(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    return FlutterDocumentHandle(registry: var_registry, id: var_id);
  }

  @protected
  FlutterDocumentSummary sse_decode_flutter_document_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_flutter_document_handle(deserializer);
    var var_format = sse_decode_flutter_book_format(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_logicalUnitCount = sse_decode_usize(deserializer);
    return FlutterDocumentSummary(
      handle: var_handle,
      format: var_format,
      title: var_title,
      logicalUnitCount: var_logicalUnitCount,
    );
  }

  @protected
  FlutterHighlightColor sse_decode_flutter_highlight_color(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterHighlightColor.values[inner];
  }

  @protected
  FlutterOpenRequest sse_decode_flutter_open_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_localId = sse_decode_String(deserializer);
    var var_pathKey = sse_decode_String(deserializer);
    var var_formatHint = sse_decode_opt_box_autoadd_flutter_book_format(
      deserializer,
    );
    return FlutterOpenRequest(
      localId: var_localId,
      pathKey: var_pathKey,
      formatHint: var_formatHint,
    );
  }

  @protected
  FlutterRenderedBuffer sse_decode_flutter_rendered_buffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_flutter_buffer_handle(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_byteLen = sse_decode_usize(deserializer);
    return FlutterRenderedBuffer(
      handle: var_handle,
      width: var_width,
      height: var_height,
      byteLen: var_byteLen,
    );
  }

  @protected
  FlutterSelectionEndpoint sse_decode_flutter_selection_endpoint(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_usize(deserializer);
    var var_rangeStart = sse_decode_usize(deserializer);
    var var_rangeEnd = sse_decode_usize(deserializer);
    var var_rect = sse_decode_flutter_selection_rect(deserializer);
    return FlutterSelectionEndpoint(
      offset: var_offset,
      rangeStart: var_rangeStart,
      rangeEnd: var_rangeEnd,
      rect: var_rect,
    );
  }

  @protected
  FlutterSelectionHandle sse_decode_flutter_selection_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registry = sse_decode_u_64(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    return FlutterSelectionHandle(registry: var_registry, id: var_id);
  }

  @protected
  FlutterSelectionRect sse_decode_flutter_selection_rect(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_left = sse_decode_f_32(deserializer);
    var var_top = sse_decode_f_32(deserializer);
    var var_right = sse_decode_f_32(deserializer);
    var var_bottom = sse_decode_f_32(deserializer);
    return FlutterSelectionRect(
      left: var_left,
      top: var_top,
      right: var_right,
      bottom: var_bottom,
    );
  }

  @protected
  FlutterSelectionSurface sse_decode_flutter_selection_surface(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_flutter_selection_handle(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_resourcePath = sse_decode_opt_String(deserializer);
    var var_raster = sse_decode_opt_box_autoadd_flutter_rendered_buffer(
      deserializer,
    );
    var var_endpoints = sse_decode_list_flutter_selection_endpoint(
      deserializer,
    );
    return FlutterSelectionSurface(
      handle: var_handle,
      width: var_width,
      height: var_height,
      text: var_text,
      resourcePath: var_resourcePath,
      raster: var_raster,
      endpoints: var_endpoints,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<FlutterAnnotation> sse_decode_list_flutter_annotation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterAnnotation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_annotation(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlutterSelectionEndpoint> sse_decode_list_flutter_selection_endpoint(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterSelectionEndpoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_selection_endpoint(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FlutterBookFormat? sse_decode_opt_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flutter_book_format(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FlutterRenderedBuffer? sse_decode_opt_box_autoadd_flutter_rendered_buffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flutter_rendered_buffer(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as FlutterBridgeImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as FlutterBridgeImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as FlutterBridgeImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_flutter_book_format(FlutterBookFormat raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_flutter_bridge_error_kind(FlutterBridgeErrorKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_flutter_highlight_color(FlutterHighlightColor raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_book_format(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_buffer_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_document_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_open_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_rendered_buffer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_selection_handle(
    FlutterSelectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_selection_handle(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_flutter_annotation(
    FlutterAnnotation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_usize(self.unit, serializer);
    sse_encode_usize(self.start, serializer);
    sse_encode_usize(self.end, serializer);
    sse_encode_flutter_highlight_color(self.color, serializer);
    sse_encode_opt_String(self.body, serializer);
  }

  @protected
  void sse_encode_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_bridge_error(
    FlutterBridgeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_flutter_bridge_error_kind(
    FlutterBridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.registry, serializer);
    sse_encode_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.registry, serializer);
    sse_encode_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_flutter_document_summary(
    FlutterDocumentSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_document_handle(self.handle, serializer);
    sse_encode_flutter_book_format(self.format, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_usize(self.logicalUnitCount, serializer);
  }

  @protected
  void sse_encode_flutter_highlight_color(
    FlutterHighlightColor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.localId, serializer);
    sse_encode_String(self.pathKey, serializer);
    sse_encode_opt_box_autoadd_flutter_book_format(self.formatHint, serializer);
  }

  @protected
  void sse_encode_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_buffer_handle(self.handle, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_usize(self.byteLen, serializer);
  }

  @protected
  void sse_encode_flutter_selection_endpoint(
    FlutterSelectionEndpoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.offset, serializer);
    sse_encode_usize(self.rangeStart, serializer);
    sse_encode_usize(self.rangeEnd, serializer);
    sse_encode_flutter_selection_rect(self.rect, serializer);
  }

  @protected
  void sse_encode_flutter_selection_handle(
    FlutterSelectionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.registry, serializer);
    sse_encode_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_flutter_selection_rect(
    FlutterSelectionRect self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.left, serializer);
    sse_encode_f_32(self.top, serializer);
    sse_encode_f_32(self.right, serializer);
    sse_encode_f_32(self.bottom, serializer);
  }

  @protected
  void sse_encode_flutter_selection_surface(
    FlutterSelectionSurface self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_selection_handle(self.handle, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.resourcePath, serializer);
    sse_encode_opt_box_autoadd_flutter_rendered_buffer(self.raster, serializer);
    sse_encode_list_flutter_selection_endpoint(self.endpoints, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_flutter_annotation(
    List<FlutterAnnotation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_annotation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flutter_selection_endpoint(
    List<FlutterSelectionEndpoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_selection_endpoint(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flutter_book_format(
    FlutterBookFormat? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flutter_book_format(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flutter_rendered_buffer(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class FlutterBridgeImpl extends RustOpaque implements FlutterBridge {
  // Not to be used by end users
  FlutterBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FlutterBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FlutterBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterBridgePtr,
  );

  bool cancel({required BigInt id}) =>
      RustLib.instance.api.crateApiFlutterBridgeCancel(that: this, id: id);

  Future<FlutterAnnotation> createAnnotation({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required BigInt start,
    required BigInt end,
    required FlutterHighlightColor color,
    String? body,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeCreateAnnotation(
    that: this,
    document: document,
    unit: unit,
    start: start,
    end: end,
    color: color,
    body: body,
    cancellationId: cancellationId,
  );

  BigInt createCancellation() =>
      RustLib.instance.api.crateApiFlutterBridgeCreateCancellation(that: this);

  Future<bool> deleteAnnotation({
    required FlutterDocumentHandle document,
    required String id,
  }) => RustLib.instance.api.crateApiFlutterBridgeDeleteAnnotation(
    that: this,
    document: document,
    id: id,
  );

  Future<List<FlutterAnnotation>> listAnnotations({
    required FlutterDocumentHandle document,
  }) => RustLib.instance.api.crateApiFlutterBridgeListAnnotations(
    that: this,
    document: document,
  );

  Future<FlutterDocumentSummary> openDocument({
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeOpenDocument(
    that: this,
    request: request,
    cancellationId: cancellationId,
  );

  bool releaseBuffer({required FlutterBufferHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeReleaseBuffer(that: this, handle: handle);

  bool releaseCancellation({required BigInt id}) => RustLib.instance.api
      .crateApiFlutterBridgeReleaseCancellation(that: this, id: id);

  bool releaseDocument({required FlutterDocumentHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeReleaseDocument(that: this, handle: handle);

  bool releaseSelection({required FlutterSelectionHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeReleaseSelection(that: this, handle: handle);

  Future<FlutterRenderedBuffer> renderPage({
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeRenderPage(
    that: this,
    document: document,
    page: page,
    scale: scale,
    cancellationId: cancellationId,
  );

  Future<FlutterSelectionSurface> selectionSurface({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required double scale,
    required double width,
    required double fontSize,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeSelectionSurface(
    that: this,
    document: document,
    unit: unit,
    scale: scale,
    width: width,
    fontSize: fontSize,
    cancellationId: cancellationId,
  );

  Uint8List takeBuffer({required FlutterBufferHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeTakeBuffer(that: this, handle: handle);

  Future<bool> updateAnnotation({
    required FlutterDocumentHandle document,
    required String id,
    required FlutterHighlightColor color,
    String? body,
  }) => RustLib.instance.api.crateApiFlutterBridgeUpdateAnnotation(
    that: this,
    document: document,
    id: id,
    color: color,
    body: body,
  );
}
