// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 963458893;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'shosai_flutter_bridge',
        ioDirectory: '../crates/shosai-flutter-bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiFlutterBridgeCancel({
    required FlutterBridge that,
    required BigInt id,
  });

  BigInt crateApiFlutterBridgeCreateCancellation({required FlutterBridge that});

  Future<FlutterBridge> crateApiFlutterBridgeDefault();

  FlutterBridge crateApiFlutterBridgeNew();

  Future<FlutterDocumentSummary> crateApiFlutterBridgeOpenDocument({
    required FlutterBridge that,
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  });

  bool crateApiFlutterBridgeReleaseBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  });

  bool crateApiFlutterBridgeReleaseCancellation({
    required FlutterBridge that,
    required BigInt id,
  });

  bool crateApiFlutterBridgeReleaseDocument({
    required FlutterBridge that,
    required FlutterDocumentHandle handle,
  });

  Future<FlutterRenderedBuffer> crateApiFlutterBridgeRenderPage({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  });

  Uint8List crateApiFlutterBridgeTakeBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  });

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlutterBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlutterBridge;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlutterBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiFlutterBridgeCancel({
    required FlutterBridge that,
    required BigInt id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeCancelConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeCancelConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_cancel",
        argNames: ["that", "id"],
      );

  @override
  BigInt crateApiFlutterBridgeCreateCancellation({
    required FlutterBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeCreateCancellationConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeCreateCancellationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_create_cancellation",
        argNames: ["that"],
      );

  @override
  Future<FlutterBridge> crateApiFlutterBridgeDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeDefaultConstMeta =>
      const TaskConstMeta(debugName: "FlutterBridge_default", argNames: []);

  @override
  FlutterBridge crateApiFlutterBridgeNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeNewConstMeta =>
      const TaskConstMeta(debugName: "FlutterBridge_new", argNames: []);

  @override
  Future<FlutterDocumentSummary> crateApiFlutterBridgeOpenDocument({
    required FlutterBridge that,
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_box_autoadd_flutter_open_request(request, serializer);
          sse_encode_u_64(cancellationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_flutter_document_summary,
          decodeErrorData: sse_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeOpenDocumentConstMeta,
        argValues: [that, request, cancellationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeOpenDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_open_document",
        argNames: ["that", "request", "cancellationId"],
      );

  @override
  bool crateApiFlutterBridgeReleaseBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_box_autoadd_flutter_buffer_handle(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseBufferConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseBufferConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_buffer",
        argNames: ["that", "handle"],
      );

  @override
  bool crateApiFlutterBridgeReleaseCancellation({
    required FlutterBridge that,
    required BigInt id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_u_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseCancellationConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseCancellationConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_cancellation",
        argNames: ["that", "id"],
      );

  @override
  bool crateApiFlutterBridgeReleaseDocument({
    required FlutterBridge that,
    required FlutterDocumentHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_box_autoadd_flutter_document_handle(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterBridgeReleaseDocumentConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeReleaseDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_release_document",
        argNames: ["that", "handle"],
      );

  @override
  Future<FlutterRenderedBuffer> crateApiFlutterBridgeRenderPage({
    required FlutterBridge that,
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_box_autoadd_flutter_document_handle(document, serializer);
          sse_encode_usize(page, serializer);
          sse_encode_f_32(scale, serializer);
          sse_encode_u_64(cancellationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_flutter_rendered_buffer,
          decodeErrorData: sse_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeRenderPageConstMeta,
        argValues: [that, document, page, scale, cancellationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeRenderPageConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_render_page",
        argNames: ["that", "document", "page", "scale", "cancellationId"],
      );

  @override
  Uint8List crateApiFlutterBridgeTakeBuffer({
    required FlutterBridge that,
    required FlutterBufferHandle handle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
            that,
            serializer,
          );
          sse_encode_box_autoadd_flutter_buffer_handle(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_flutter_bridge_error,
        ),
        constMeta: kCrateApiFlutterBridgeTakeBufferConstMeta,
        argValues: [that, handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterBridgeTakeBufferConstMeta =>
      const TaskConstMeta(
        debugName: "FlutterBridge_take_buffer",
        argNames: ["that", "handle"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlutterBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlutterBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge;

  @protected
  FlutterBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlutterBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterBookFormat dco_decode_box_autoadd_flutter_book_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_book_format(raw);
  }

  @protected
  FlutterBufferHandle dco_decode_box_autoadd_flutter_buffer_handle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_buffer_handle(raw);
  }

  @protected
  FlutterDocumentHandle dco_decode_box_autoadd_flutter_document_handle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_document_handle(raw);
  }

  @protected
  FlutterOpenRequest dco_decode_box_autoadd_flutter_open_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_open_request(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FlutterBookFormat dco_decode_flutter_book_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBookFormat.values[raw as int];
  }

  @protected
  FlutterBridgeError dco_decode_flutter_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterBridgeError(
      kind: dco_decode_flutter_bridge_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  FlutterBridgeErrorKind dco_decode_flutter_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterBridgeErrorKind.values[raw as int];
  }

  @protected
  FlutterBufferHandle dco_decode_flutter_buffer_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterBufferHandle(
      registry: dco_decode_u_64(arr[0]),
      id: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FlutterDocumentHandle dco_decode_flutter_document_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterDocumentHandle(
      registry: dco_decode_u_64(arr[0]),
      id: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FlutterDocumentSummary dco_decode_flutter_document_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterDocumentSummary(
      handle: dco_decode_flutter_document_handle(arr[0]),
      format: dco_decode_flutter_book_format(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      logicalUnitCount: dco_decode_usize(arr[3]),
    );
  }

  @protected
  FlutterOpenRequest dco_decode_flutter_open_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FlutterOpenRequest(
      localId: dco_decode_String(arr[0]),
      pathKey: dco_decode_String(arr[1]),
      formatHint: dco_decode_opt_box_autoadd_flutter_book_format(arr[2]),
    );
  }

  @protected
  FlutterRenderedBuffer dco_decode_flutter_rendered_buffer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterRenderedBuffer(
      handle: dco_decode_flutter_buffer_handle(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      byteLen: dco_decode_usize(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FlutterBookFormat? dco_decode_opt_box_autoadd_flutter_book_format(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_flutter_book_format(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  FlutterBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlutterBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlutterBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlutterBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterBookFormat sse_decode_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_book_format(deserializer));
  }

  @protected
  FlutterBufferHandle sse_decode_box_autoadd_flutter_buffer_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_buffer_handle(deserializer));
  }

  @protected
  FlutterDocumentHandle sse_decode_box_autoadd_flutter_document_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_document_handle(deserializer));
  }

  @protected
  FlutterOpenRequest sse_decode_box_autoadd_flutter_open_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_open_request(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FlutterBookFormat sse_decode_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterBookFormat.values[inner];
  }

  @protected
  FlutterBridgeError sse_decode_flutter_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_flutter_bridge_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return FlutterBridgeError(kind: var_kind, message: var_message);
  }

  @protected
  FlutterBridgeErrorKind sse_decode_flutter_bridge_error_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterBridgeErrorKind.values[inner];
  }

  @protected
  FlutterBufferHandle sse_decode_flutter_buffer_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registry = sse_decode_u_64(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    return FlutterBufferHandle(registry: var_registry, id: var_id);
  }

  @protected
  FlutterDocumentHandle sse_decode_flutter_document_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registry = sse_decode_u_64(deserializer);
    var var_id = sse_decode_u_64(deserializer);
    return FlutterDocumentHandle(registry: var_registry, id: var_id);
  }

  @protected
  FlutterDocumentSummary sse_decode_flutter_document_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_flutter_document_handle(deserializer);
    var var_format = sse_decode_flutter_book_format(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_logicalUnitCount = sse_decode_usize(deserializer);
    return FlutterDocumentSummary(
      handle: var_handle,
      format: var_format,
      title: var_title,
      logicalUnitCount: var_logicalUnitCount,
    );
  }

  @protected
  FlutterOpenRequest sse_decode_flutter_open_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_localId = sse_decode_String(deserializer);
    var var_pathKey = sse_decode_String(deserializer);
    var var_formatHint = sse_decode_opt_box_autoadd_flutter_book_format(
      deserializer,
    );
    return FlutterOpenRequest(
      localId: var_localId,
      pathKey: var_pathKey,
      formatHint: var_formatHint,
    );
  }

  @protected
  FlutterRenderedBuffer sse_decode_flutter_rendered_buffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_flutter_buffer_handle(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_byteLen = sse_decode_usize(deserializer);
    return FlutterRenderedBuffer(
      handle: var_handle,
      width: var_width,
      height: var_height,
      byteLen: var_byteLen,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FlutterBookFormat? sse_decode_opt_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_flutter_book_format(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlutterBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_book_format(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_buffer_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_document_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_open_request(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_bridge_error(
    FlutterBridgeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_flutter_bridge_error_kind(
    FlutterBridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.registry, serializer);
    sse_encode_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.registry, serializer);
    sse_encode_u_64(self.id, serializer);
  }

  @protected
  void sse_encode_flutter_document_summary(
    FlutterDocumentSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_document_handle(self.handle, serializer);
    sse_encode_flutter_book_format(self.format, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_usize(self.logicalUnitCount, serializer);
  }

  @protected
  void sse_encode_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.localId, serializer);
    sse_encode_String(self.pathKey, serializer);
    sse_encode_opt_box_autoadd_flutter_book_format(self.formatHint, serializer);
  }

  @protected
  void sse_encode_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_buffer_handle(self.handle, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_usize(self.byteLen, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_flutter_book_format(
    FlutterBookFormat? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_flutter_book_format(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class FlutterBridgeImpl extends RustOpaque implements FlutterBridge {
  // Not to be used by end users
  FlutterBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FlutterBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FlutterBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlutterBridgePtr,
  );

  bool cancel({required BigInt id}) =>
      RustLib.instance.api.crateApiFlutterBridgeCancel(that: this, id: id);

  BigInt createCancellation() =>
      RustLib.instance.api.crateApiFlutterBridgeCreateCancellation(that: this);

  Future<FlutterDocumentSummary> openDocument({
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeOpenDocument(
    that: this,
    request: request,
    cancellationId: cancellationId,
  );

  bool releaseBuffer({required FlutterBufferHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeReleaseBuffer(that: this, handle: handle);

  bool releaseCancellation({required BigInt id}) => RustLib.instance.api
      .crateApiFlutterBridgeReleaseCancellation(that: this, id: id);

  bool releaseDocument({required FlutterDocumentHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeReleaseDocument(that: this, handle: handle);

  Future<FlutterRenderedBuffer> renderPage({
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  }) => RustLib.instance.api.crateApiFlutterBridgeRenderPage(
    that: this,
    document: document,
    page: page,
    scale: scale,
    cancellationId: cancellationId,
  );

  Uint8List takeBuffer({required FlutterBufferHandle handle}) => RustLib
      .instance
      .api
      .crateApiFlutterBridgeTakeBuffer(that: this, handle: handle);
}
