// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlutterBridgePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr;

  @protected
  FlutterBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  FlutterBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  FlutterBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FlutterBookFormat dco_decode_box_autoadd_flutter_book_format(dynamic raw);

  @protected
  FlutterBufferHandle dco_decode_box_autoadd_flutter_buffer_handle(dynamic raw);

  @protected
  FlutterDocumentHandle dco_decode_box_autoadd_flutter_document_handle(
    dynamic raw,
  );

  @protected
  FlutterOpenRequest dco_decode_box_autoadd_flutter_open_request(dynamic raw);

  @protected
  FlutterRenderedBuffer dco_decode_box_autoadd_flutter_rendered_buffer(
    dynamic raw,
  );

  @protected
  FlutterSelectionHandle dco_decode_box_autoadd_flutter_selection_handle(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FlutterAnnotation dco_decode_flutter_annotation(dynamic raw);

  @protected
  FlutterBookFormat dco_decode_flutter_book_format(dynamic raw);

  @protected
  FlutterBridgeError dco_decode_flutter_bridge_error(dynamic raw);

  @protected
  FlutterBridgeErrorKind dco_decode_flutter_bridge_error_kind(dynamic raw);

  @protected
  FlutterBufferHandle dco_decode_flutter_buffer_handle(dynamic raw);

  @protected
  FlutterDocumentHandle dco_decode_flutter_document_handle(dynamic raw);

  @protected
  FlutterDocumentSummary dco_decode_flutter_document_summary(dynamic raw);

  @protected
  FlutterHighlightColor dco_decode_flutter_highlight_color(dynamic raw);

  @protected
  FlutterOpenRequest dco_decode_flutter_open_request(dynamic raw);

  @protected
  FlutterRenderedBuffer dco_decode_flutter_rendered_buffer(dynamic raw);

  @protected
  FlutterSelectionCaret dco_decode_flutter_selection_caret(dynamic raw);

  @protected
  FlutterSelectionEndpoint dco_decode_flutter_selection_endpoint(dynamic raw);

  @protected
  FlutterSelectionHandle dco_decode_flutter_selection_handle(dynamic raw);

  @protected
  FlutterSelectionRect dco_decode_flutter_selection_rect(dynamic raw);

  @protected
  FlutterSelectionSurface dco_decode_flutter_selection_surface(dynamic raw);

  @protected
  FlutterSelectionVisualLine dco_decode_flutter_selection_visual_line(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<FlutterAnnotation> dco_decode_list_flutter_annotation(dynamic raw);

  @protected
  List<FlutterSelectionCaret> dco_decode_list_flutter_selection_caret(
    dynamic raw,
  );

  @protected
  List<FlutterSelectionEndpoint> dco_decode_list_flutter_selection_endpoint(
    dynamic raw,
  );

  @protected
  List<FlutterSelectionVisualLine>
  dco_decode_list_flutter_selection_visual_line(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FlutterBookFormat? dco_decode_opt_box_autoadd_flutter_book_format(
    dynamic raw,
  );

  @protected
  FlutterRenderedBuffer? dco_decode_opt_box_autoadd_flutter_rendered_buffer(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  FlutterBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FlutterBookFormat sse_decode_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBufferHandle sse_decode_box_autoadd_flutter_buffer_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentHandle sse_decode_box_autoadd_flutter_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterOpenRequest sse_decode_box_autoadd_flutter_open_request(
    SseDeserializer deserializer,
  );

  @protected
  FlutterRenderedBuffer sse_decode_box_autoadd_flutter_rendered_buffer(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionHandle sse_decode_box_autoadd_flutter_selection_handle(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FlutterAnnotation sse_decode_flutter_annotation(SseDeserializer deserializer);

  @protected
  FlutterBookFormat sse_decode_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridgeError sse_decode_flutter_bridge_error(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBridgeErrorKind sse_decode_flutter_bridge_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBufferHandle sse_decode_flutter_buffer_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentHandle sse_decode_flutter_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDocumentSummary sse_decode_flutter_document_summary(
    SseDeserializer deserializer,
  );

  @protected
  FlutterHighlightColor sse_decode_flutter_highlight_color(
    SseDeserializer deserializer,
  );

  @protected
  FlutterOpenRequest sse_decode_flutter_open_request(
    SseDeserializer deserializer,
  );

  @protected
  FlutterRenderedBuffer sse_decode_flutter_rendered_buffer(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionCaret sse_decode_flutter_selection_caret(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionEndpoint sse_decode_flutter_selection_endpoint(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionHandle sse_decode_flutter_selection_handle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionRect sse_decode_flutter_selection_rect(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionSurface sse_decode_flutter_selection_surface(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSelectionVisualLine sse_decode_flutter_selection_visual_line(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<FlutterAnnotation> sse_decode_list_flutter_annotation(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterSelectionCaret> sse_decode_list_flutter_selection_caret(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterSelectionEndpoint> sse_decode_list_flutter_selection_endpoint(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterSelectionVisualLine>
  sse_decode_list_flutter_selection_visual_line(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FlutterBookFormat? sse_decode_opt_box_autoadd_flutter_book_format(
    SseDeserializer deserializer,
  );

  @protected
  FlutterRenderedBuffer? sse_decode_opt_box_autoadd_flutter_rendered_buffer(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_flutter_book_format(
    FlutterBookFormat raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_flutter_book_format(
      cst_encode_flutter_book_format(raw),
    );
  }

  @protected
  ffi.Pointer<wire_cst_flutter_buffer_handle>
  cst_encode_box_autoadd_flutter_buffer_handle(FlutterBufferHandle raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_flutter_buffer_handle();
    cst_api_fill_to_wire_flutter_buffer_handle(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_flutter_document_handle>
  cst_encode_box_autoadd_flutter_document_handle(FlutterDocumentHandle raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_flutter_document_handle();
    cst_api_fill_to_wire_flutter_document_handle(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_flutter_open_request>
  cst_encode_box_autoadd_flutter_open_request(FlutterOpenRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_flutter_open_request();
    cst_api_fill_to_wire_flutter_open_request(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_flutter_rendered_buffer>
  cst_encode_box_autoadd_flutter_rendered_buffer(FlutterRenderedBuffer raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_flutter_rendered_buffer();
    cst_api_fill_to_wire_flutter_rendered_buffer(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_flutter_selection_handle>
  cst_encode_box_autoadd_flutter_selection_handle(FlutterSelectionHandle raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_flutter_selection_handle();
    cst_api_fill_to_wire_flutter_selection_handle(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_flutter_annotation>
  cst_encode_list_flutter_annotation(List<FlutterAnnotation> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_flutter_annotation(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_flutter_annotation(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_flutter_selection_caret>
  cst_encode_list_flutter_selection_caret(List<FlutterSelectionCaret> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_flutter_selection_caret(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_flutter_selection_caret(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_flutter_selection_endpoint>
  cst_encode_list_flutter_selection_endpoint(
    List<FlutterSelectionEndpoint> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_flutter_selection_endpoint(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_flutter_selection_endpoint(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_flutter_selection_visual_line>
  cst_encode_list_flutter_selection_visual_line(
    List<FlutterSelectionVisualLine> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_flutter_selection_visual_line(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_flutter_selection_visual_line(
        raw[i],
        ans.ref.ptr[i],
      );
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_encode_list_prim_u_32_strict(
    Uint32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_flutter_book_format(
    FlutterBookFormat? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_flutter_book_format(raw);
  }

  @protected
  ffi.Pointer<wire_cst_flutter_rendered_buffer>
  cst_encode_opt_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_flutter_rendered_buffer(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_flutter_buffer_handle(
    FlutterBufferHandle apiObj,
    ffi.Pointer<wire_cst_flutter_buffer_handle> wireObj,
  ) {
    cst_api_fill_to_wire_flutter_buffer_handle(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_flutter_document_handle(
    FlutterDocumentHandle apiObj,
    ffi.Pointer<wire_cst_flutter_document_handle> wireObj,
  ) {
    cst_api_fill_to_wire_flutter_document_handle(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_flutter_open_request(
    FlutterOpenRequest apiObj,
    ffi.Pointer<wire_cst_flutter_open_request> wireObj,
  ) {
    cst_api_fill_to_wire_flutter_open_request(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer apiObj,
    ffi.Pointer<wire_cst_flutter_rendered_buffer> wireObj,
  ) {
    cst_api_fill_to_wire_flutter_rendered_buffer(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_flutter_selection_handle(
    FlutterSelectionHandle apiObj,
    ffi.Pointer<wire_cst_flutter_selection_handle> wireObj,
  ) {
    cst_api_fill_to_wire_flutter_selection_handle(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_flutter_annotation(
    FlutterAnnotation apiObj,
    wire_cst_flutter_annotation wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.unit = cst_encode_usize(apiObj.unit);
    wireObj.start = cst_encode_usize(apiObj.start);
    wireObj.end = cst_encode_usize(apiObj.end);
    wireObj.color = cst_encode_flutter_highlight_color(apiObj.color);
    wireObj.body = cst_encode_opt_String(apiObj.body);
  }

  @protected
  void cst_api_fill_to_wire_flutter_bridge_error(
    FlutterBridgeError apiObj,
    wire_cst_flutter_bridge_error wireObj,
  ) {
    wireObj.kind = cst_encode_flutter_bridge_error_kind(apiObj.kind);
    wireObj.message = cst_encode_String(apiObj.message);
  }

  @protected
  void cst_api_fill_to_wire_flutter_buffer_handle(
    FlutterBufferHandle apiObj,
    wire_cst_flutter_buffer_handle wireObj,
  ) {
    wireObj.registry = cst_encode_u_64(apiObj.registry);
    wireObj.id = cst_encode_u_64(apiObj.id);
  }

  @protected
  void cst_api_fill_to_wire_flutter_document_handle(
    FlutterDocumentHandle apiObj,
    wire_cst_flutter_document_handle wireObj,
  ) {
    wireObj.registry = cst_encode_u_64(apiObj.registry);
    wireObj.id = cst_encode_u_64(apiObj.id);
  }

  @protected
  void cst_api_fill_to_wire_flutter_document_summary(
    FlutterDocumentSummary apiObj,
    wire_cst_flutter_document_summary wireObj,
  ) {
    cst_api_fill_to_wire_flutter_document_handle(apiObj.handle, wireObj.handle);
    wireObj.format = cst_encode_flutter_book_format(apiObj.format);
    wireObj.title = cst_encode_opt_String(apiObj.title);
    wireObj.logical_unit_count = cst_encode_usize(apiObj.logicalUnitCount);
  }

  @protected
  void cst_api_fill_to_wire_flutter_open_request(
    FlutterOpenRequest apiObj,
    wire_cst_flutter_open_request wireObj,
  ) {
    wireObj.local_id = cst_encode_String(apiObj.localId);
    wireObj.path_key = cst_encode_String(apiObj.pathKey);
    wireObj.format_hint = cst_encode_opt_box_autoadd_flutter_book_format(
      apiObj.formatHint,
    );
  }

  @protected
  void cst_api_fill_to_wire_flutter_rendered_buffer(
    FlutterRenderedBuffer apiObj,
    wire_cst_flutter_rendered_buffer wireObj,
  ) {
    cst_api_fill_to_wire_flutter_buffer_handle(apiObj.handle, wireObj.handle);
    wireObj.width = cst_encode_u_32(apiObj.width);
    wireObj.height = cst_encode_u_32(apiObj.height);
    wireObj.byte_len = cst_encode_usize(apiObj.byteLen);
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_caret(
    FlutterSelectionCaret apiObj,
    wire_cst_flutter_selection_caret wireObj,
  ) {
    wireObj.offset = cst_encode_usize(apiObj.offset);
    wireObj.x = cst_encode_f_32(apiObj.x);
    wireObj.top = cst_encode_f_32(apiObj.top);
    wireObj.bottom = cst_encode_f_32(apiObj.bottom);
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_endpoint(
    FlutterSelectionEndpoint apiObj,
    wire_cst_flutter_selection_endpoint wireObj,
  ) {
    wireObj.offset = cst_encode_usize(apiObj.offset);
    wireObj.range_start = cst_encode_usize(apiObj.rangeStart);
    wireObj.range_end = cst_encode_usize(apiObj.rangeEnd);
    cst_api_fill_to_wire_flutter_selection_rect(apiObj.rect, wireObj.rect);
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_handle(
    FlutterSelectionHandle apiObj,
    wire_cst_flutter_selection_handle wireObj,
  ) {
    wireObj.registry = cst_encode_u_64(apiObj.registry);
    wireObj.id = cst_encode_u_64(apiObj.id);
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_rect(
    FlutterSelectionRect apiObj,
    wire_cst_flutter_selection_rect wireObj,
  ) {
    wireObj.left = cst_encode_f_32(apiObj.left);
    wireObj.top = cst_encode_f_32(apiObj.top);
    wireObj.right = cst_encode_f_32(apiObj.right);
    wireObj.bottom = cst_encode_f_32(apiObj.bottom);
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_surface(
    FlutterSelectionSurface apiObj,
    wire_cst_flutter_selection_surface wireObj,
  ) {
    cst_api_fill_to_wire_flutter_selection_handle(
      apiObj.handle,
      wireObj.handle,
    );
    wireObj.width = cst_encode_f_32(apiObj.width);
    wireObj.height = cst_encode_f_32(apiObj.height);
    wireObj.text = cst_encode_String(apiObj.text);
    wireObj.resource_path = cst_encode_opt_String(apiObj.resourcePath);
    wireObj.raster = cst_encode_opt_box_autoadd_flutter_rendered_buffer(
      apiObj.raster,
    );
    wireObj.endpoints = cst_encode_list_flutter_selection_endpoint(
      apiObj.endpoints,
    );
    wireObj.grapheme_boundaries = cst_encode_list_prim_u_32_strict(
      apiObj.graphemeBoundaries,
    );
    wireObj.word_boundaries = cst_encode_list_prim_u_32_strict(
      apiObj.wordBoundaries,
    );
    wireObj.visual_lines = cst_encode_list_flutter_selection_visual_line(
      apiObj.visualLines,
    );
  }

  @protected
  void cst_api_fill_to_wire_flutter_selection_visual_line(
    FlutterSelectionVisualLine apiObj,
    wire_cst_flutter_selection_visual_line wireObj,
  ) {
    wireObj.carets = cst_encode_list_flutter_selection_caret(apiObj.carets);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_flutter_book_format(FlutterBookFormat raw);

  @protected
  int cst_encode_flutter_bridge_error_kind(FlutterBridgeErrorKind raw);

  @protected
  int cst_encode_flutter_highlight_color(FlutterHighlightColor raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    FlutterBridge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_selection_handle(
    FlutterSelectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_annotation(
    FlutterAnnotation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_book_format(
    FlutterBookFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_bridge_error(
    FlutterBridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_bridge_error_kind(
    FlutterBridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_buffer_handle(
    FlutterBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_document_handle(
    FlutterDocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_document_summary(
    FlutterDocumentSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_highlight_color(
    FlutterHighlightColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_open_request(
    FlutterOpenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_rendered_buffer(
    FlutterRenderedBuffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_caret(
    FlutterSelectionCaret self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_endpoint(
    FlutterSelectionEndpoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_handle(
    FlutterSelectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_rect(
    FlutterSelectionRect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_surface(
    FlutterSelectionSurface self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_selection_visual_line(
    FlutterSelectionVisualLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_flutter_annotation(
    List<FlutterAnnotation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_selection_caret(
    List<FlutterSelectionCaret> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_selection_endpoint(
    List<FlutterSelectionEndpoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_selection_visual_line(
    List<FlutterSelectionVisualLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_flutter_book_format(
    FlutterBookFormat? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_rendered_buffer(
    FlutterRenderedBuffer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_cancel(
    int that,
    int id,
  ) {
    return _wire__crate__api__FlutterBridge_cancel(that, id);
  }

  late final _wire__crate__api__FlutterBridge_cancelPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(ffi.UintPtr, ffi.Uint64)
        >
      >('frbgen_shosai_flutter_wire__crate__api__FlutterBridge_cancel');
  late final _wire__crate__api__FlutterBridge_cancel =
      _wire__crate__api__FlutterBridge_cancelPtr
          .asFunction<WireSyncRust2DartDco Function(int, int)>();

  void wire__crate__api__FlutterBridge_create_annotation(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
    int unit,
    int start,
    int end,
    int color,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> body,
    int cancellation_id,
  ) {
    return _wire__crate__api__FlutterBridge_create_annotation(
      port_,
      that,
      document,
      unit,
      start,
      end,
      color,
      body,
      cancellation_id,
    );
  }

  late final _wire__crate__api__FlutterBridge_create_annotationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
            ffi.UintPtr,
            ffi.UintPtr,
            ffi.UintPtr,
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_create_annotation',
      );
  late final _wire__crate__api__FlutterBridge_create_annotation =
      _wire__crate__api__FlutterBridge_create_annotationPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
              int,
              int,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_create_cancellation(
    int that,
  ) {
    return _wire__crate__api__FlutterBridge_create_cancellation(that);
  }

  late final _wire__crate__api__FlutterBridge_create_cancellationPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_create_cancellation',
      );
  late final _wire__crate__api__FlutterBridge_create_cancellation =
      _wire__crate__api__FlutterBridge_create_cancellationPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__crate__api__FlutterBridge_default(int port_) {
    return _wire__crate__api__FlutterBridge_default(port_);
  }

  late final _wire__crate__api__FlutterBridge_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_default',
      );
  late final _wire__crate__api__FlutterBridge_default =
      _wire__crate__api__FlutterBridge_defaultPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__FlutterBridge_delete_annotation(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__FlutterBridge_delete_annotation(
      port_,
      that,
      document,
      id,
    );
  }

  late final _wire__crate__api__FlutterBridge_delete_annotationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_delete_annotation',
      );
  late final _wire__crate__api__FlutterBridge_delete_annotation =
      _wire__crate__api__FlutterBridge_delete_annotationPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__FlutterBridge_list_annotations(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
  ) {
    return _wire__crate__api__FlutterBridge_list_annotations(
      port_,
      that,
      document,
    );
  }

  late final _wire__crate__api__FlutterBridge_list_annotationsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_list_annotations',
      );
  late final _wire__crate__api__FlutterBridge_list_annotations =
      _wire__crate__api__FlutterBridge_list_annotationsPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_new() {
    return _wire__crate__api__FlutterBridge_new();
  }

  late final _wire__crate__api__FlutterBridge_newPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_new',
      );
  late final _wire__crate__api__FlutterBridge_new =
      _wire__crate__api__FlutterBridge_newPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__FlutterBridge_open_document(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_open_request> request,
    int cancellation_id,
  ) {
    return _wire__crate__api__FlutterBridge_open_document(
      port_,
      that,
      request,
      cancellation_id,
    );
  }

  late final _wire__crate__api__FlutterBridge_open_documentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_open_request>,
            ffi.Uint64,
          )
        >
      >('frbgen_shosai_flutter_wire__crate__api__FlutterBridge_open_document');
  late final _wire__crate__api__FlutterBridge_open_document =
      _wire__crate__api__FlutterBridge_open_documentPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_open_request>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_release_buffer(
    int that,
    ffi.Pointer<wire_cst_flutter_buffer_handle> handle,
  ) {
    return _wire__crate__api__FlutterBridge_release_buffer(that, handle);
  }

  late final _wire__crate__api__FlutterBridge_release_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_buffer_handle>,
          )
        >
      >('frbgen_shosai_flutter_wire__crate__api__FlutterBridge_release_buffer');
  late final _wire__crate__api__FlutterBridge_release_buffer =
      _wire__crate__api__FlutterBridge_release_bufferPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_flutter_buffer_handle>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_release_cancellation(
    int that,
    int id,
  ) {
    return _wire__crate__api__FlutterBridge_release_cancellation(that, id);
  }

  late final _wire__crate__api__FlutterBridge_release_cancellationPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(ffi.UintPtr, ffi.Uint64)
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_release_cancellation',
      );
  late final _wire__crate__api__FlutterBridge_release_cancellation =
      _wire__crate__api__FlutterBridge_release_cancellationPtr
          .asFunction<WireSyncRust2DartDco Function(int, int)>();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_release_document(
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> handle,
  ) {
    return _wire__crate__api__FlutterBridge_release_document(that, handle);
  }

  late final _wire__crate__api__FlutterBridge_release_documentPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_release_document',
      );
  late final _wire__crate__api__FlutterBridge_release_document =
      _wire__crate__api__FlutterBridge_release_documentPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_release_selection(
    int that,
    ffi.Pointer<wire_cst_flutter_selection_handle> handle,
  ) {
    return _wire__crate__api__FlutterBridge_release_selection(that, handle);
  }

  late final _wire__crate__api__FlutterBridge_release_selectionPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_selection_handle>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_release_selection',
      );
  late final _wire__crate__api__FlutterBridge_release_selection =
      _wire__crate__api__FlutterBridge_release_selectionPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_flutter_selection_handle>,
            )
          >();

  void wire__crate__api__FlutterBridge_render_page(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
    int page,
    double scale,
    int cancellation_id,
  ) {
    return _wire__crate__api__FlutterBridge_render_page(
      port_,
      that,
      document,
      page,
      scale,
      cancellation_id,
    );
  }

  late final _wire__crate__api__FlutterBridge_render_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
            ffi.UintPtr,
            ffi.Float,
            ffi.Uint64,
          )
        >
      >('frbgen_shosai_flutter_wire__crate__api__FlutterBridge_render_page');
  late final _wire__crate__api__FlutterBridge_render_page =
      _wire__crate__api__FlutterBridge_render_pagePtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
              int,
              double,
              int,
            )
          >();

  void wire__crate__api__FlutterBridge_selection_surface(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
    int unit,
    double scale,
    double width,
    double font_size,
    int cancellation_id,
  ) {
    return _wire__crate__api__FlutterBridge_selection_surface(
      port_,
      that,
      document,
      unit,
      scale,
      width,
      font_size,
      cancellation_id,
    );
  }

  late final _wire__crate__api__FlutterBridge_selection_surfacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
            ffi.UintPtr,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Uint64,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_selection_surface',
      );
  late final _wire__crate__api__FlutterBridge_selection_surface =
      _wire__crate__api__FlutterBridge_selection_surfacePtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
              int,
              double,
              double,
              double,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_take_buffer(
    int that,
    ffi.Pointer<wire_cst_flutter_buffer_handle> handle,
  ) {
    return _wire__crate__api__FlutterBridge_take_buffer(that, handle);
  }

  late final _wire__crate__api__FlutterBridge_take_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_buffer_handle>,
          )
        >
      >('frbgen_shosai_flutter_wire__crate__api__FlutterBridge_take_buffer');
  late final _wire__crate__api__FlutterBridge_take_buffer =
      _wire__crate__api__FlutterBridge_take_bufferPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_flutter_buffer_handle>,
            )
          >();

  void wire__crate__api__FlutterBridge_update_annotation(
    int port_,
    int that,
    ffi.Pointer<wire_cst_flutter_document_handle> document,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    int color,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> body,
  ) {
    return _wire__crate__api__FlutterBridge_update_annotation(
      port_,
      that,
      document,
      id,
      color,
      body,
    );
  }

  late final _wire__crate__api__FlutterBridge_update_annotationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_flutter_document_handle>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_update_annotation',
      );
  late final _wire__crate__api__FlutterBridge_update_annotation =
      _wire__crate__api__FlutterBridge_update_annotationPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_flutter_document_handle>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__FlutterBridge_with_database_path(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> database_path,
  ) {
    return _wire__crate__api__FlutterBridge_with_database_path(database_path);
  }

  late final _wire__crate__api__FlutterBridge_with_database_pathPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shosai_flutter_wire__crate__api__FlutterBridge_with_database_path',
      );
  late final _wire__crate__api__FlutterBridge_with_database_path =
      _wire__crate__api__FlutterBridge_with_database_pathPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__init_app(int port_) {
    return _wire__crate__api__init_app(port_);
  }

  late final _wire__crate__api__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_shosai_flutter_wire__crate__api__init_app',
      );
  late final _wire__crate__api__init_app = _wire__crate__api__init_appPtr
      .asFunction<void Function(int)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shosai_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shosai_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridge =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_flutter_book_format(int value) {
    return _cst_new_box_autoadd_flutter_book_format(value);
  }

  late final _cst_new_box_autoadd_flutter_book_formatPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_shosai_flutter_cst_new_box_autoadd_flutter_book_format',
      );
  late final _cst_new_box_autoadd_flutter_book_format =
      _cst_new_box_autoadd_flutter_book_formatPtr
          .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<wire_cst_flutter_buffer_handle>
  cst_new_box_autoadd_flutter_buffer_handle() {
    return _cst_new_box_autoadd_flutter_buffer_handle();
  }

  late final _cst_new_box_autoadd_flutter_buffer_handlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_flutter_buffer_handle> Function()
        >
      >('frbgen_shosai_flutter_cst_new_box_autoadd_flutter_buffer_handle');
  late final _cst_new_box_autoadd_flutter_buffer_handle =
      _cst_new_box_autoadd_flutter_buffer_handlePtr
          .asFunction<ffi.Pointer<wire_cst_flutter_buffer_handle> Function()>();

  ffi.Pointer<wire_cst_flutter_document_handle>
  cst_new_box_autoadd_flutter_document_handle() {
    return _cst_new_box_autoadd_flutter_document_handle();
  }

  late final _cst_new_box_autoadd_flutter_document_handlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_flutter_document_handle> Function()
        >
      >('frbgen_shosai_flutter_cst_new_box_autoadd_flutter_document_handle');
  late final _cst_new_box_autoadd_flutter_document_handle =
      _cst_new_box_autoadd_flutter_document_handlePtr
          .asFunction<
            ffi.Pointer<wire_cst_flutter_document_handle> Function()
          >();

  ffi.Pointer<wire_cst_flutter_open_request>
  cst_new_box_autoadd_flutter_open_request() {
    return _cst_new_box_autoadd_flutter_open_request();
  }

  late final _cst_new_box_autoadd_flutter_open_requestPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_flutter_open_request> Function()
        >
      >('frbgen_shosai_flutter_cst_new_box_autoadd_flutter_open_request');
  late final _cst_new_box_autoadd_flutter_open_request =
      _cst_new_box_autoadd_flutter_open_requestPtr
          .asFunction<ffi.Pointer<wire_cst_flutter_open_request> Function()>();

  ffi.Pointer<wire_cst_flutter_rendered_buffer>
  cst_new_box_autoadd_flutter_rendered_buffer() {
    return _cst_new_box_autoadd_flutter_rendered_buffer();
  }

  late final _cst_new_box_autoadd_flutter_rendered_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_flutter_rendered_buffer> Function()
        >
      >('frbgen_shosai_flutter_cst_new_box_autoadd_flutter_rendered_buffer');
  late final _cst_new_box_autoadd_flutter_rendered_buffer =
      _cst_new_box_autoadd_flutter_rendered_bufferPtr
          .asFunction<
            ffi.Pointer<wire_cst_flutter_rendered_buffer> Function()
          >();

  ffi.Pointer<wire_cst_flutter_selection_handle>
  cst_new_box_autoadd_flutter_selection_handle() {
    return _cst_new_box_autoadd_flutter_selection_handle();
  }

  late final _cst_new_box_autoadd_flutter_selection_handlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_flutter_selection_handle> Function()
        >
      >('frbgen_shosai_flutter_cst_new_box_autoadd_flutter_selection_handle');
  late final _cst_new_box_autoadd_flutter_selection_handle =
      _cst_new_box_autoadd_flutter_selection_handlePtr
          .asFunction<
            ffi.Pointer<wire_cst_flutter_selection_handle> Function()
          >();

  ffi.Pointer<wire_cst_list_flutter_annotation> cst_new_list_flutter_annotation(
    int len,
  ) {
    return _cst_new_list_flutter_annotation(len);
  }

  late final _cst_new_list_flutter_annotationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_flutter_annotation> Function(ffi.Int32)
        >
      >('frbgen_shosai_flutter_cst_new_list_flutter_annotation');
  late final _cst_new_list_flutter_annotation =
      _cst_new_list_flutter_annotationPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_flutter_annotation> Function(int)
          >();

  ffi.Pointer<wire_cst_list_flutter_selection_caret>
  cst_new_list_flutter_selection_caret(int len) {
    return _cst_new_list_flutter_selection_caret(len);
  }

  late final _cst_new_list_flutter_selection_caretPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_flutter_selection_caret> Function(ffi.Int32)
        >
      >('frbgen_shosai_flutter_cst_new_list_flutter_selection_caret');
  late final _cst_new_list_flutter_selection_caret =
      _cst_new_list_flutter_selection_caretPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_flutter_selection_caret> Function(int)
          >();

  ffi.Pointer<wire_cst_list_flutter_selection_endpoint>
  cst_new_list_flutter_selection_endpoint(int len) {
    return _cst_new_list_flutter_selection_endpoint(len);
  }

  late final _cst_new_list_flutter_selection_endpointPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_flutter_selection_endpoint> Function(
            ffi.Int32,
          )
        >
      >('frbgen_shosai_flutter_cst_new_list_flutter_selection_endpoint');
  late final _cst_new_list_flutter_selection_endpoint =
      _cst_new_list_flutter_selection_endpointPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_flutter_selection_endpoint> Function(int)
          >();

  ffi.Pointer<wire_cst_list_flutter_selection_visual_line>
  cst_new_list_flutter_selection_visual_line(int len) {
    return _cst_new_list_flutter_selection_visual_line(len);
  }

  late final _cst_new_list_flutter_selection_visual_linePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_flutter_selection_visual_line> Function(
            ffi.Int32,
          )
        >
      >('frbgen_shosai_flutter_cst_new_list_flutter_selection_visual_line');
  late final _cst_new_list_flutter_selection_visual_line =
      _cst_new_list_flutter_selection_visual_linePtr
          .asFunction<
            ffi.Pointer<wire_cst_list_flutter_selection_visual_line> Function(
              int,
            )
          >();

  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_new_list_prim_u_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_32_strict(len);
  }

  late final _cst_new_list_prim_u_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(ffi.Int32)
        >
      >('frbgen_shosai_flutter_cst_new_list_prim_u_32_strict');
  late final _cst_new_list_prim_u_32_strict = _cst_new_list_prim_u_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_shosai_flutter_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_flutter_document_handle extends ffi.Struct {
  @ffi.Uint64()
  external int registry;

  @ffi.Uint64()
  external int id;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_flutter_open_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> local_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path_key;

  external ffi.Pointer<ffi.Int32> format_hint;
}

final class wire_cst_flutter_buffer_handle extends ffi.Struct {
  @ffi.Uint64()
  external int registry;

  @ffi.Uint64()
  external int id;
}

final class wire_cst_flutter_selection_handle extends ffi.Struct {
  @ffi.Uint64()
  external int registry;

  @ffi.Uint64()
  external int id;
}

final class wire_cst_flutter_rendered_buffer extends ffi.Struct {
  external wire_cst_flutter_buffer_handle handle;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.UintPtr()
  external int byte_len;
}

final class wire_cst_flutter_annotation extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.UintPtr()
  external int unit;

  @ffi.UintPtr()
  external int start;

  @ffi.UintPtr()
  external int end;

  @ffi.Int32()
  external int color;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> body;
}

final class wire_cst_list_flutter_annotation extends ffi.Struct {
  external ffi.Pointer<wire_cst_flutter_annotation> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_flutter_selection_caret extends ffi.Struct {
  @ffi.UintPtr()
  external int offset;

  @ffi.Float()
  external double x;

  @ffi.Float()
  external double top;

  @ffi.Float()
  external double bottom;
}

final class wire_cst_list_flutter_selection_caret extends ffi.Struct {
  external ffi.Pointer<wire_cst_flutter_selection_caret> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_flutter_selection_rect extends ffi.Struct {
  @ffi.Float()
  external double left;

  @ffi.Float()
  external double top;

  @ffi.Float()
  external double right;

  @ffi.Float()
  external double bottom;
}

final class wire_cst_flutter_selection_endpoint extends ffi.Struct {
  @ffi.UintPtr()
  external int offset;

  @ffi.UintPtr()
  external int range_start;

  @ffi.UintPtr()
  external int range_end;

  external wire_cst_flutter_selection_rect rect;
}

final class wire_cst_list_flutter_selection_endpoint extends ffi.Struct {
  external ffi.Pointer<wire_cst_flutter_selection_endpoint> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_flutter_selection_visual_line extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_flutter_selection_caret> carets;
}

final class wire_cst_list_flutter_selection_visual_line extends ffi.Struct {
  external ffi.Pointer<wire_cst_flutter_selection_visual_line> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_flutter_bridge_error extends ffi.Struct {
  @ffi.Int32()
  external int kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}

final class wire_cst_flutter_document_summary extends ffi.Struct {
  external wire_cst_flutter_document_handle handle;

  @ffi.Int32()
  external int format;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  @ffi.UintPtr()
  external int logical_unit_count;
}

final class wire_cst_flutter_selection_surface extends ffi.Struct {
  external wire_cst_flutter_selection_handle handle;

  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> resource_path;

  external ffi.Pointer<wire_cst_flutter_rendered_buffer> raster;

  external ffi.Pointer<wire_cst_list_flutter_selection_endpoint> endpoints;

  external ffi.Pointer<wire_cst_list_prim_u_32_strict> grapheme_boundaries;

  external ffi.Pointer<wire_cst_list_prim_u_32_strict> word_boundaries;

  external ffi.Pointer<wire_cst_list_flutter_selection_visual_line>
  visual_lines;
}
